version: "3.8"
services:
    server:
      image: server
      build:
        context: ./server
        dockerfile: Dockerfile
      container_name: ${SERVER_HOST}
      env_file: .env
      environment:
        REDIS_HOST: redis_cache
        REDIS_PORT: 6379
      ports:
        - ${SERVER_PORT}:${SERVER_PORT}
      depends_on:
        - redis_cache
    nginx:
      image: reverse-proxy
      restart: always
      build: 
        context: ./nginx
        dockerfile: Dockerfile
      container_name: ${NGINX_HOST}
      env_file: .env
      ports:
          - ${NGINX_PORT}:${NGINX_PORT}
    redis_cache:
      container_name: redis
      image: redis:alpine3.16
      ports:
        - 6379:6379
